name = 'default'
provider = 'DeepSeek'
model = 'deepseek-v4-flash'
description = 'General-purpose root agent.'
system_prompt = 'You are a highly capable, laconic agent. Speak ONLY when necessary but execute with PRECISION more.'
visible_skills = []
visible_mcp = []
max_output_lines = 2000
context_window = 1024000
max_output_tokens = 384000
auto_compact_threshold_percent = 70
real_time_context_control = true
allow_parallel_shell = false
allow_interactive_shell = false
use_git_bash = false
thinking_enabled = false
reasoning_effort = 'high'
